### ISSUE TITLE
Cannot use import statement outside a module in Remix/Vite

### ISSUE THREAD

**Issue by piotrkulpinski** [knocklabs/javascript#19]
Hi, 

I'm trying to migrate my app from NextJS to Remix running on Vite, but can't get Knock to work with this stack. 

If I try to initialize the knock client, I get the following error: 

```
[vite] Internal server error: Cannot use import statement outside a module
      at internalCompileFunction (node:internal/vm:73:18)
      at wrapSafe (node:internal/modules/cjs/loader:1153:20)
      at Module._compile (node:internal/modules/cjs/loader:1205:27)
      at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
      at Module.load (node:internal/modules/cjs/loader:1091:32)
      at Module._load (node:internal/modules/cjs/loader:938:12)
      at cjsLoader (node:internal/modules/esm/translators:284:17)
      at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:234:7)
      at ModuleJob.run (node:internal/modules/esm/module_job:217:25)
      at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
      at async nodeImport (file:///.../node_modules/vite/dist/node/chunks/dep-bb8a8339.js:56097:17)
      at async ssrImport (file:///.../node_modules/vite/dist/node/chunks/dep-bb8a8339.js:55990:24)
      at async eval (/.../app/components/navs/nav-notifications.tsx:5:31)
      at async instantiateModule (file:///.../node_modules/vite/dist/node/chunks/dep-bb8a8339.js:56052:9)
```

I assume this is similar to knocklabs/javascript#20 but I decided to open a new issue since the cause may be different. 

Does anyone have any solution to this.

**Comment by kylemcd** [comment]
This should be fixed by #22
